from level1 import *

__all__ = ["level1"]

TARGETS_COUNT           = {1:TARGETS_COUNT1}
TARGETS_PICS            = {1:TARGETS_PICS1}
TARGETS_WIDTHS          = {1:TARGETS_WIDTHS1}
TARGETS_HEIGHTS         = {1:TARGETS_HEIGHTS1}
TARGETS_ANGLES          = {1:TARGETS_ANGLES1}
TARGETS_START_POSITION  = {1:TARGETS_START_POSITION1}
TARGETS_MOVE_FUNCTION   = {1:TARGETS_MOVE_FUNCTION1}
TARGETS_HEALTH          = {1:TARGETS_HEALTH1}
TARGETS_VALUE           = {1:TARGETS_VALUE1}
TARGETS_BONUSES         = {1:TARGETS_BONUSES1}